[package]
name = "bedrock-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
proto = { path ="./proto"}
rand = { version = "0.9.0", features = [] }
lazy_static = "1.5.0"
