[package]
name = "proto"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = "1.43.0"
rak-rs = { version = "0.3.3", default-features = false, features = [ "async_tokio", "mcpe" ] }
log = "0.4.25"